### ISSUE TITLE
Update Link for Arm64

### ISSUE THREAD

**Issue by engageub** [XternA/gaga-node#1]
Hi,
Could you please update the link for Linux Arm64 to https://assets.coreservice.io/public/package/61/app-market-gaga-pro/1.0.4/app-market-gaga-pro-1_0_4.tar.gz

Please see the latest links from https://dashboard.gaganode.com/install_run 
They are different for amd64 and aarch64.

Thank you

**Comment by XternA** [comment]
Changes have been applied, new image docker image available. This will now be marked as resolved.
